export const EMOJI_RECENT_STORAGE_KEY = "veritas_ticket_emoji_recent";
export const EMOJI_RECENT_LIMIT = 24;

export const EMOJI_CATEGORIES = [
  {
    id: "smileys",
    icon: "mdi:emoticon-outline",
    emojis: [
      { e: "😀", k: "sourire grin smile happy joyeux" },
      { e: "😃", k: "sourire yeux smile happy" },
      { e: "😄", k: "sourire rire smile laugh" },
      { e: "😁", k: "sourire dents grin" },
      { e: "😆", k: "rire squint laugh" },
      { e: "😅", k: "sueur nervosite sweat nervous oops" },
      { e: "🤣", k: "mort de rire rofl lol mdr" },
      { e: "😂", k: "larmes rire joy tears lol mdr" },
      { e: "🙂", k: "sourire leger slight smile" },
      { e: "🙃", k: "sourire inverse upside down" },
      { e: "😉", k: "clin d oeil wink" },
      { e: "😊", k: "sourire blush content happy" },
      { e: "😇", k: "ange innocent halo angel" },
      { e: "🥰", k: "amour coeurs love hearts" },
      { e: "😍", k: "yeux coeur love crush" },
      { e: "🤩", k: "etoiles wow star struck" },
      { e: "😘", k: "bisou kiss" },
      { e: "😗", k: "bisou kiss" },
      { e: "☺️", k: "sourire relaxed" },
      { e: "😚", k: "bisou yeux fermes kiss" },
      { e: "😙", k: "bisou sourire kiss" },
      { e: "🥲", k: "larme sourire tear grateful" },
      { e: "😋", k: "miam savoureux yum tasty" },
      { e: "😛", k: "langue tongue" },
      { e: "😜", k: "langue clin d oeil tongue wink" },
      { e: "🤪", k: "fou crazy zany" },
      { e: "😝", k: "langue yeux fermes tongue" },
      { e: "🤑", k: "argent money dollar" },
      { e: "🤗", k: "calin hug" },
      { e: "🤭", k: "oops surprise hand" },
      { e: "🤫", k: "chut silence shh" },
      { e: "🤔", k: "reflexion think hmm" },
      { e: "🤐", k: "fermeture eclair zip mute" },
      { e: "🤨", k: "sourcil raised eyebrow skeptic" },
      { e: "😐", k: "neutre neutral" },
      { e: "😑", k: "inexpressif expressionless" },
      { e: "😶", k: "sans bouche silent" },
      { e: "😏", k: "sourire en coin smirk" },
      { e: "😒", k: "pas content unamused" },
      { e: "🙄", k: "yeux au ciel roll eyes" },
      { e: "😬", k: "grimace awkward" },
      { e: "🤥", k: "menteur lie pinocchio" },
      { e: "😌", k: "soulage relieved" },
      { e: "😔", k: "pensif sad pensive" },
      { e: "😪", k: "somnolent sleepy" },
      { e: "🤤", k: "bave drool" },
      { e: "😴", k: "dodo sleep zzz" },
      { e: "😷", k: "masque malade mask sick" },
      { e: "🤒", k: "fievre thermometer sick" },
      { e: "🤕", k: "bandage blessure hurt" },
      { e: "🤢", k: "nausee sick nauseous" },
      { e: "🤮", k: "vomi vomit" },
      { e: "🤧", k: "atcchou sneeze" },
      { e: "🥵", k: "chaud hot" },
      { e: "🥶", k: "froid cold freeze" },
      { e: "🥴", k: "etourdi woozy" },
      { e: "😵", k: "vertige dizzy" },
      { e: "🤯", k: "explose mind blown" },
      { e: "🤠", k: "cowboy" },
      { e: "🥳", k: "fete party celebrate" },
      { e: "😎", k: "lunettes cool sunglasses" },
      { e: "🤓", k: "nerd lunettes geek" },
      { e: "🧐", k: "monocle inspect" },
      { e: "😕", k: "confus confused" },
      { e: "😟", k: "inquiet worried" },
      { e: "🙁", k: "pas content frown" },
      { e: "☹️", k: "triste frown sad" },
      { e: "😮", k: "surprise open mouth wow" },
      { e: "😯", k: "surpris hushed" },
      { e: "😲", k: "etonne astonished" },
      { e: "😳", k: "rougir flushed embarrassed" },
      { e: "🥺", k: "supplie pleading puppy" },
      { e: "😦", k: "frowning" },
      { e: "😧", k: "angoisse anguished" },
      { e: "😨", k: "peur fear scared" },
      { e: "😰", k: "sueur froide anxious" },
      { e: "😥", k: "decu disappointed relieved" },
      { e: "😢", k: "pleure cry sad larme" },
      { e: "😭", k: "pleure fort sob cry" },
      { e: "😱", k: "cri scream fear" },
      { e: "😖", k: "contrarie confounded" },
      { e: "😣", k: "persevering" },
      { e: "😞", k: "decu disappointed" },
      { e: "😓", k: "sueur downcast" },
      { e: "😩", k: "epuise weary tired" },
      { e: "😫", k: "fatigue tired" },
      { e: "🥱", k: "baillement yawn" },
      { e: "😤", k: "vapeur frustrated hmpf" },
      { e: "😡", k: "colere angry mad" },
      { e: "😠", k: "fache angry" },
      { e: "🤬", k: "insulte swearing" },
      { e: "😈", k: "diable smile devil" },
      { e: "👿", k: "diable angry devil" },
      { e: "💀", k: "crane skull mort death" },
      { e: "☠️", k: "tete de mort skull bones" },
      { e: "💩", k: "caca poop" },
      { e: "🤡", k: "clown" },
      { e: "👹", k: "ogre demon" },
      { e: "👺", k: "gobelin goblin" },
      { e: "👻", k: "fantome ghost" },
      { e: "👽", k: "alien extra terrestre" },
      { e: "👾", k: "monstre space invader" },
      { e: "🤖", k: "robot" },
      { e: "🎃", k: "citrouille halloween pumpkin" },
      { e: "😺", k: "chat sourire cat smile" },
      { e: "😸", k: "chat rire cat grin" },
      { e: "😹", k: "chat larmes cat joy" },
      { e: "😻", k: "chat coeur cat love" },
      { e: "😼", k: "chat smirk" },
      { e: "😽", k: "chat bisou cat kiss" },
      { e: "🙀", k: "chat scream" },
      { e: "😿", k: "chat pleure cat cry" },
      { e: "😾", k: "chat fache cat angry" }
    ]
  },
  {
    id: "gestures",
    icon: "mdi:hand-wave",
    emojis: [
      { e: "👋", k: "salut wave hello bye coucou" },
      { e: "🤚", k: "main levee raised hand" },
      { e: "🖐️", k: "main ouverte palm" },
      { e: "✋", k: "stop hand" },
      { e: "🖖", k: "vulcain spock" },
      { e: "👌", k: "ok parfait" },
      { e: "🤌", k: "pinces pinched fingers italien" },
      { e: "🤏", k: "un peu pinch small" },
      { e: "✌️", k: "victoire peace victory" },
      { e: "🤞", k: "doigts croises luck" },
      { e: "🤟", k: "love you" },
      { e: "🤘", k: "rock horns" },
      { e: "🤙", k: "call me telephone" },
      { e: "👈", k: "gauche left" },
      { e: "👉", k: "droite right" },
      { e: "👆", k: "haut up" },
      { e: "🖕", k: "doigt d honneur middle" },
      { e: "👇", k: "bas down" },
      { e: "☝️", k: "index up point" },
      { e: "👍", k: "pouce ok like yes top" },
      { e: "👎", k: "pouce down no bad" },
      { e: "✊", k: "poing fist" },
      { e: "👊", k: "punch poing" },
      { e: "🤛", k: "poing gauche" },
      { e: "🤜", k: "poing droit" },
      { e: "👏", k: "applaudir clap bravo" },
      { e: "🙌", k: "hands up yes" },
      { e: "👐", k: "mains ouvertes open" },
      { e: "🤲", k: "paumes palms" },
      { e: "🤝", k: "poignee handshake accord deal" },
      { e: "🙏", k: "merci please priere thanks please" },
      { e: "✍️", k: "ecrire write" },
      { e: "💅", k: "vernis nail polish" },
      { e: "🤳", k: "selfie" },
      { e: "💪", k: "muscle fort strong biceps" },
      { e: "🦾", k: "bras mecanique mechanical" },
      { e: "🦿", k: "jambe mecanique" },
      { e: "🦵", k: "jambe leg" },
      { e: "🦶", k: "pied foot" },
      { e: "👂", k: "oreille ear" },
      { e: "👃", k: "nez nose" },
      { e: "🧠", k: "cerveau brain" },
      { e: "👀", k: "yeux eyes regarder look" },
      { e: "👁️", k: "oeil eye" },
      { e: "👅", k: "langue tongue" },
      { e: "👄", k: "bouche lips" },
      { e: "💋", k: "bisou kiss lips" },
      { e: "🩸", k: "sang blood" }
    ]
  },
  {
    id: "people",
    icon: "mdi:account-group-outline",
    emojis: [
      { e: "👶", k: "bebe baby" },
      { e: "🧒", k: "enfant child" },
      { e: "👦", k: "garcon boy" },
      { e: "👧", k: "fille girl" },
      { e: "🧑", k: "personne person" },
      { e: "👱", k: "blond" },
      { e: "👨", k: "homme man" },
      { e: "👩", k: "femme woman" },
      { e: "🧔", k: "barbe beard" },
      { e: "🧓", k: "senior older" },
      { e: "👴", k: "vieux old man" },
      { e: "👵", k: "vieille old woman" },
      { e: "🙍", k: "fronce frowning" },
      { e: "🙎", k: "boude pouting" },
      { e: "🙅", k: "non refuse no" },
      { e: "🙆", k: "ok geste" },
      { e: "💁", k: "information tip" },
      { e: "🙋", k: "leve la main raise" },
      { e: "🧏", k: "sourd deaf" },
      { e: "🙇", k: "salut bow desole sorry" },
      { e: "🤦", k: "facepalm face palm" },
      { e: "🤷", k: "shrug je sais pas dunno" },
      { e: "👮", k: "police" },
      { e: "🕵️", k: "detective" },
      { e: "💂", k: "garde guard" },
      { e: "🥷", k: "ninja" },
      { e: "👷", k: "ouvrier construction" },
      { e: "🤴", k: "prince" },
      { e: "👸", k: "princesse princess" },
      { e: "👳", k: "turban" },
      { e: "👲", k: "chapeau chinois" },
      { e: "🧕", k: "hijab" },
      { e: "🤵", k: "smoking tuxedo" },
      { e: "👰", k: "mariee bride" },
      { e: "🤰", k: "enceinte pregnant" },
      { e: "🤱", k: "allaitement" },
      { e: "👼", k: "ange baby angel" },
      { e: "🎅", k: "pere noel santa" },
      { e: "🤶", k: "mere noel" },
      { e: "🦸", k: "super heros superhero" },
      { e: "🦹", k: "super vilain supervillain" },
      { e: "🧙", k: "mage wizard" },
      { e: "🧚", k: "fee fairy" },
      { e: "🧛", k: "vampire" },
      { e: "🧜", k: "sirene mermaid" },
      { e: "🧝", k: "elfe elf" },
      { e: "🧞", k: "genie" },
      { e: "🧟", k: "zombie" },
      { e: "💆", k: "massage" },
      { e: "💇", k: "coiffure haircut" },
      { e: "🚶", k: "marche walk" },
      { e: "🧍", k: "debout standing" },
      { e: "🧎", k: "agenouille kneeling" },
      { e: "🏃", k: "course run" },
      { e: "💃", k: "danse dance" },
      { e: "🕺", k: "danseur dancer" },
      { e: "🕴️", k: "costume levite" },
      { e: "👯", k: "oreilles lapin party" },
      { e: "🧖", k: "sauna" },
      { e: "🧗", k: "escalade climb" },
      { e: "🏇", k: "equitation horse" },
      { e: "⛷️", k: "ski" },
      { e: "🏂", k: "snowboard" },
      { e: "🏌️", k: "golf" },
      { e: "🏄", k: "surf" },
      { e: "🚣", k: "rame row" },
      { e: "🏊", k: "nage swim" },
      { e: "⛹️", k: "basket ball" },
      { e: "🏋️", k: "musculation weights" },
      { e: "🚴", k: "velo bike" },
      { e: "🚵", k: "vtt mountain bike" },
      { e: "🤸", k: "roue cartwheel" },
      { e: "🤼", k: "lutte wrestle" },
      { e: "🤽", k: "water polo" },
      { e: "🤾", k: "handball" },
      { e: "🤹", k: "jongle juggle" },
      { e: "🧘", k: "yoga meditation" },
      { e: "🛀", k: "bain bath" },
      { e: "🛌", k: "lit bed sleep" },
      { e: "👪", k: "famille family" },
      { e: "👫", k: "couple" },
      { e: "👬", k: "deux hommes" },
      { e: "👭", k: "deux femmes" },
      { e: "💏", k: "bisou couple kiss" },
      { e: "💑", k: "couple coeur love" }
    ]
  },
  {
    id: "animals",
    icon: "mdi:paw",
    emojis: [
      { e: "🐶", k: "chien dog" },
      { e: "🐱", k: "chat cat" },
      { e: "🐭", k: "souris mouse" },
      { e: "🐹", k: "hamster" },
      { e: "🐰", k: "lapin rabbit bunny" },
      { e: "🦊", k: "renard fox" },
      { e: "🐻", k: "ours bear" },
      { e: "🐼", k: "panda" },
      { e: "🐻‍❄️", k: "ours polaire polar" },
      { e: "🐨", k: "koala" },
      { e: "🐯", k: "tigre tiger" },
      { e: "🦁", k: "lion" },
      { e: "🐮", k: "vache cow" },
      { e: "🐷", k: "cochon pig" },
      { e: "🐸", k: "grenouille frog" },
      { e: "🐵", k: "singe monkey" },
      { e: "🙈", k: "singe yeux see no" },
      { e: "🙉", k: "singe oreilles hear no" },
      { e: "🙊", k: "singe bouche speak no" },
      { e: "🐒", k: "singe monkey" },
      { e: "🐔", k: "poule chicken" },
      { e: "🐧", k: "pingouin penguin" },
      { e: "🐦", k: "oiseau bird" },
      { e: "🐤", k: "poussin chick" },
      { e: "🐣", k: "oeuf poussin hatching" },
      { e: "🐥", k: "poussin front" },
      { e: "🦆", k: "canard duck" },
      { e: "🦅", k: "aigle eagle" },
      { e: "🦉", k: "hibou owl" },
      { e: "🦇", k: "chauve souris bat" },
      { e: "🐺", k: "loup wolf" },
      { e: "🐗", k: "sanglier boar" },
      { e: "🐴", k: "cheval horse" },
      { e: "🦄", k: "licorne unicorn" },
      { e: "🐝", k: "abeille bee" },
      { e: "🪱", k: "ver worm" },
      { e: "🐛", k: "chenille bug" },
      { e: "🦋", k: "papillon butterfly" },
      { e: "🐌", k: "escargot snail" },
      { e: "🐞", k: "coccinelle ladybug" },
      { e: "🐜", k: "fourmi ant" },
      { e: "🪰", k: "mouche fly" },
      { e: "🪲", k: "scarabee beetle" },
      { e: "🪳", k: "cafard cockroach" },
      { e: "🦟", k: "moustique mosquito" },
      { e: "🦗", k: "criquet cricket" },
      { e: "🕷️", k: "araignee spider" },
      { e: "🕸️", k: "toile web" },
      { e: "🦂", k: "scorpion" },
      { e: "🐢", k: "tortue turtle" },
      { e: "🐍", k: "serpent snake" },
      { e: "🦎", k: "lezard lizard" },
      { e: "🦖", k: "t rex dinosaure" },
      { e: "🦕", k: "sauropode dinosaure" },
      { e: "🐙", k: "poulpe octopus" },
      { e: "🦑", k: "calamar squid" },
      { e: "🦐", k: "crevette shrimp" },
      { e: "🦞", k: "homard lobster" },
      { e: "🦀", k: "crabe crab" },
      { e: "🐡", k: "poisson globe blowfish" },
      { e: "🐠", k: "poisson tropical" },
      { e: "🐟", k: "poisson fish" },
      { e: "🐬", k: "dauphin dolphin" },
      { e: "🐳", k: "baleine whale" },
      { e: "🐋", k: "baleine whale" },
      { e: "🦈", k: "requin shark" },
      { e: "🐊", k: "crocodile" },
      { e: "🐅", k: "tigre tiger" },
      { e: "🐆", k: "leopard" },
      { e: "🦓", k: "zebre zebra" },
      { e: "🦍", k: "gorille gorilla" },
      { e: "🦧", k: "orang outan" },
      { e: "🐘", k: "elephant" },
      { e: "🦛", k: "hippopotame hippo" },
      { e: "🦏", k: "rhinoceros rhino" },
      { e: "🐪", k: "dromadaire camel" },
      { e: "🐫", k: "chameau camel" },
      { e: "🦒", k: "girafe giraffe" },
      { e: "🦘", k: "kangourou kangaroo" },
      { e: "🦬", k: "bison" },
      { e: "🐃", k: "buffle buffalo" },
      { e: "🐂", k: "boeuf ox" },
      { e: "🐄", k: "vache cow" },
      { e: "🐎", k: "cheval horse" },
      { e: "🐖", k: "cochon pig" },
      { e: "🐏", k: "belier ram" },
      { e: "🐑", k: "mouton sheep" },
      { e: "🦙", k: "lama llama" },
      { e: "🐐", k: "chevre goat" },
      { e: "🦌", k: "cerf deer" },
      { e: "🐕", k: "chien dog" },
      { e: "🐩", k: "caniche poodle" },
      { e: "🦮", k: "chien guide" },
      { e: "🐈", k: "chat cat" },
      { e: "🪶", k: "plume feather" },
      { e: "🐓", k: "coq rooster" },
      { e: "🦃", k: "dinde turkey" },
      { e: "🦤", k: "dodo" },
      { e: "🦚", k: "paon peacock" },
      { e: "🦜", k: "perroquet parrot" },
      { e: "🦢", k: "cygne swan" },
      { e: "🦩", k: "flamant flamingo" },
      { e: "🕊️", k: "colombe dove paix peace" },
      { e: "🐇", k: "lapin rabbit" },
      { e: "🦝", k: "raton laveur raccoon" },
      { e: "🦨", k: "mouffette skunk" },
      { e: "🦡", k: "blaireau badger" },
      { e: "🦫", k: "castor beaver" },
      { e: "🦦", k: "loutre otter" },
      { e: "🦥", k: "paresseux sloth" },
      { e: "🐁", k: "souris mouse" },
      { e: "🐀", k: "rat" },
      { e: "🐿️", k: "ecureuil chipmunk" },
      { e: "🦔", k: "herisson hedgehog" },
      { e: "🐾", k: "empreintes paw traces" },
      { e: "🐉", k: "dragon" },
      { e: "🐲", k: "dragon face" },
      { e: "🌵", k: "cactus" },
      { e: "🎄", k: "sapin noel christmas tree" },
      { e: "🌲", k: "sapin evergreen" },
      { e: "🌳", k: "arbre tree" },
      { e: "🌴", k: "palmier palm" },
      { e: "🌱", k: "pousse seedling" },
      { e: "🌿", k: "herbe herb" },
      { e: "☘️", k: "trefle shamrock" },
      { e: "🍀", k: "trefle quatre luck clover" },
      { e: "🎍", k: "bambou" },
      { e: "🪴", k: "plante pot" },
      { e: "🎋", k: "tanabata" },
      { e: "🍃", k: "feuille leaf vent" },
      { e: "🍂", k: "feuille automne fallen" },
      { e: "🍁", k: "erable maple" },
      { e: "🍄", k: "champignon mushroom" },
      { e: "🐚", k: "coquillage shell" },
      { e: "🪨", k: "rocher rock" },
      { e: "🌾", k: "riz rice" },
      { e: "💐", k: "bouquet flowers" },
      { e: "🌷", k: "tulipe tulip" },
      { e: "🌹", k: "rose" },
      { e: "🥀", k: "rose fanee wilted" },
      { e: "🌺", k: "hibiscus" },
      { e: "🌸", k: "cerisier sakura blossom" },
      { e: "🌼", k: "fleur blossom" },
      { e: "🌻", k: "tournesol sunflower" },
      { e: "🌞", k: "soleil visagé sun" },
      { e: "🌝", k: "pleine lune visage" },
      { e: "🌛", k: "lune premier quartier" },
      { e: "🌜", k: "lune dernier quartier" },
      { e: "🌚", k: "nouvelle lune visage" },
      { e: "🌕", k: "pleine lune full moon" },
      { e: "🌖", k: "lune gibbeuse" },
      { e: "🌗", k: "lune dernier quartier" },
      { e: "🌘", k: "lune croissant" },
      { e: "🌑", k: "nouvelle lune new moon" },
      { e: "🌒", k: "croissant lune" },
      { e: "🌓", k: "premier quartier" },
      { e: "🌔", k: "gibbeuse" },
      { e: "🌙", k: "croissant crescent moon" },
      { e: "🌎", k: "terre americas earth" },
      { e: "🌍", k: "terre europe afrique earth" },
      { e: "🌏", k: "terre asie earth" },
      { e: "🪐", k: "saturne planet" },
      { e: "💫", k: "etincelle dizzy star" },
      { e: "⭐", k: "etoile star" },
      { e: "🌟", k: "etoile brillante glowing" },
      { e: "✨", k: "etincelles sparkles magie" },
      { e: "⚡", k: "eclair lightning voltage" },
      { e: "☄️", k: "comete comet" },
      { e: "💥", k: "explosion boom collide" },
      { e: "🔥", k: "feu fire flamme chaud hot" },
      { e: "🌪️", k: "tornade tornado" },
      { e: "🌈", k: "arc en ciel rainbow" },
      { e: "☀️", k: "soleil sun" },
      { e: "🌤️", k: "soleil nuage" },
      { e: "⛅", k: "nuageux cloudy" },
      { e: "🌥️", k: "nuage soleil" },
      { e: "☁️", k: "nuage cloud" },
      { e: "🌦️", k: "pluie soleil" },
      { e: "🌧️", k: "pluie rain" },
      { e: "⛈️", k: "orage storm" },
      { e: "🌩️", k: "eclair nuage" },
      { e: "🌨️", k: "neige snow" },
      { e: "❄️", k: "flocon snowflake" },
      { e: "☃️", k: "bonhomme neige snowman" },
      { e: "⛄", k: "bonhomme neige snowman" },
      { e: "🌬️", k: "vent wind" },
      { e: "💨", k: "dash vent" },
      { e: "💧", k: "goutte droplet" },
      { e: "💦", k: "gouttes sweat drops" },
      { e: "☔", k: "parapluie umbrella rain" },
      { e: "☂️", k: "parapluie umbrella" },
      { e: "🌊", k: "vague wave ocean" },
      { e: "🌫️", k: "brouillard fog" }
    ]
  },
  {
    id: "food",
    icon: "mdi:food-apple",
    emojis: [
      { e: "🍇", k: "raisin grapes" },
      { e: "🍈", k: "melon" },
      { e: "🍉", k: "pasteque watermelon" },
      { e: "🍊", k: "orange tangerine" },
      { e: "🍋", k: "citron lemon" },
      { e: "🍌", k: "banane banana" },
      { e: "🍍", k: "ananas pineapple" },
      { e: "🥭", k: "mangue mango" },
      { e: "🍎", k: "pomme rouge apple" },
      { e: "🍏", k: "pomme verte apple" },
      { e: "🍐", k: "poire pear" },
      { e: "🍑", k: "peche peach" },
      { e: "🍒", k: "cerises cherries" },
      { e: "🍓", k: "fraise strawberry" },
      { e: "🫐", k: "myrtilles blueberries" },
      { e: "🥝", k: "kiwi" },
      { e: "🍅", k: "tomate tomato" },
      { e: "🫒", k: "olive" },
      { e: "🥥", k: "noix de coco coconut" },
      { e: "🥑", k: "avocat avocado" },
      { e: "🍆", k: "aubergine eggplant" },
      { e: "🥔", k: "pomme de terre potato" },
      { e: "🥕", k: "carotte carrot" },
      { e: "🌽", k: "mais corn" },
      { e: "🌶️", k: "piment hot pepper" },
      { e: "🫑", k: "poivron bell pepper" },
      { e: "🥒", k: "concombre cucumber" },
      { e: "🥬", k: "salade leafy" },
      { e: "🥦", k: "brocoli broccoli" },
      { e: "🧄", k: "ail garlic" },
      { e: "🧅", k: "oignon onion" },
      { e: "🍄", k: "champignon mushroom" },
      { e: "🥜", k: "cacahuete peanut" },
      { e: "🌰", k: "chataigne chestnut" },
      { e: "🍞", k: "pain bread" },
      { e: "🥐", k: "croissant" },
      { e: "🥖", k: "baguette" },
      { e: "🫓", k: "galette flatbread" },
      { e: "🥨", k: "bretzel pretzel" },
      { e: "🥯", k: "bagel" },
      { e: "🥞", k: "pancakes" },
      { e: "🧇", k: "gaufre waffle" },
      { e: "🧀", k: "fromage cheese" },
      { e: "🍖", k: "viande meat" },
      { e: "🍗", k: "poulet poultry" },
      { e: "🥩", k: "steak" },
      { e: "🥓", k: "bacon" },
      { e: "🍔", k: "burger hamburger" },
      { e: "🍟", k: "frites fries" },
      { e: "🍕", k: "pizza" },
      { e: "🌭", k: "hot dog" },
      { e: "🥪", k: "sandwich" },
      { e: "🌮", k: "taco" },
      { e: "🌯", k: "burrito" },
      { e: "🫔", k: "tamale" },
      { e: "🥙", k: "kebab stuffed" },
      { e: "🧆", k: "falafel" },
      { e: "🥚", k: "oeuf egg" },
      { e: "🍳", k: "oeuf plat cooking" },
      { e: "🥘", k: "paella pan" },
      { e: "🍲", k: "pot stew" },
      { e: "🫕", k: "fondue" },
      { e: "🥣", k: "bol bowl" },
      { e: "🥗", k: "salade salad" },
      { e: "🍿", k: "popcorn" },
      { e: "🧈", k: "beurre butter" },
      { e: "🧂", k: "sel salt" },
      { e: "🥫", k: "conserve canned" },
      { e: "🍱", k: "bento" },
      { e: "🍘", k: "cracker riz" },
      { e: "🍙", k: "onigiri rice ball" },
      { e: "🍚", k: "riz rice" },
      { e: "🍛", k: "curry" },
      { e: "🍜", k: "ramen nouilles" },
      { e: "🍝", k: "spaghetti pasta" },
      { e: "🍠", k: "patate douce" },
      { e: "🍢", k: "oden" },
      { e: "🍣", k: "sushi" },
      { e: "🍤", k: "crevette fried" },
      { e: "🍥", k: "kamaboko" },
      { e: "🥮", k: "moon cake" },
      { e: "🍡", k: "dango" },
      { e: "🥟", k: "ravioli dumpling" },
      { e: "🥠", k: "biscuit fortune" },
      { e: "🥡", k: "takeout" },
      { e: "🦀", k: "crabe crab" },
      { e: "🍦", k: "glace ice cream" },
      { e: "🍧", k: "granite shaved ice" },
      { e: "🍨", k: "glace coupe" },
      { e: "🍩", k: "donut doughnut" },
      { e: "🍪", k: "cookie biscuit" },
      { e: "🎂", k: "gateau anniversaire cake birthday" },
      { e: "🍰", k: "part gateau shortcake" },
      { e: "🧁", k: "cupcake" },
      { e: "🥧", k: "tarte pie" },
      { e: "🍫", k: "chocolat chocolate" },
      { e: "🍬", k: "bonbon candy" },
      { e: "🍭", k: "sucette lollipop" },
      { e: "🍮", k: "flan custard" },
      { e: "🍯", k: "miel honey" },
      { e: "🍼", k: "biberon baby bottle" },
      { e: "🥛", k: "lait milk" },
      { e: "☕", k: "cafe coffee the tea" },
      { e: "🫖", k: "theiere teapot" },
      { e: "🍵", k: "the tea" },
      { e: "🍶", k: "sake" },
      { e: "🍾", k: "champagne bouteille" },
      { e: "🍷", k: "vin wine" },
      { e: "🍸", k: "cocktail" },
      { e: "🍹", k: "tropical drink" },
      { e: "🍺", k: "biere beer" },
      { e: "🍻", k: "pintes beers sante cheers" },
      { e: "🥂", k: "trinquer cheers toast" },
      { e: "🥃", k: "whisky tumbler" },
      { e: "🥤", k: "soda cup" },
      { e: "🧋", k: "bubble tea" },
      { e: "🧃", k: "jus juice box" },
      { e: "🧉", k: "mate" },
      { e: "🧊", k: "glace ice cube" },
      { e: "🥢", k: "baguettes chopsticks" },
      { e: "🍽️", k: "couvert assiette dining" },
      { e: "🍴", k: "fourchette couteau fork" },
      { e: "🥄", k: "cuillere spoon" },
      { e: "🔪", k: "couteau knife" },
      { e: "🫙", k: "bocal jar" }
    ]
  },
  {
    id: "travel",
    icon: "mdi:airplane",
    emojis: [
      { e: "🚗", k: "voiture car" },
      { e: "🚕", k: "taxi" },
      { e: "🚙", k: "suv" },
      { e: "🚌", k: "bus" },
      { e: "🚎", k: "trolleybus" },
      { e: "🏎️", k: "course racing car" },
      { e: "🚓", k: "police car" },
      { e: "🚑", k: "ambulance" },
      { e: "🚒", k: "pompier fire truck" },
      { e: "🚐", k: "minibus van" },
      { e: "🛻", k: "pickup" },
      { e: "🚚", k: "camion delivery truck" },
      { e: "🚛", k: "poids lourd articulated" },
      { e: "🚜", k: "tracteur tractor" },
      { e: "🦯", k: "canne blanche" },
      { e: "🦽", k: "fauteuil roulant" },
      { e: "🦼", k: "fauteuil motorise" },
      { e: "🛴", k: "trottinette scooter" },
      { e: "🚲", k: "velo bicycle" },
      { e: "🛵", k: "scooter moto" },
      { e: "🏍️", k: "moto motorcycle" },
      { e: "🛺", k: "tuk tuk" },
      { e: "🚨", k: "gyrophare siren alert" },
      { e: "🚔", k: "police oncoming" },
      { e: "🚍", k: "bus oncoming" },
      { e: "🚘", k: "voiture oncoming" },
      { e: "🚖", k: "taxi oncoming" },
      { e: "🚡", k: "cable car" },
      { e: "🚠", k: "telepherique gondola" },
      { e: "🚟", k: "suspension railway" },
      { e: "🚃", k: "wagon railway" },
      { e: "🚋", k: "tram" },
      { e: "🚞", k: "train montagne" },
      { e: "🚝", k: "monorail" },
      { e: "🚄", k: "tgv bullet train" },
      { e: "🚅", k: "shinkansen bullet" },
      { e: "🚈", k: "light rail" },
      { e: "🚂", k: "locomotive steam" },
      { e: "🚆", k: "train" },
      { e: "🚇", k: "metro" },
      { e: "🚊", k: "tramway" },
      { e: "🚉", k: "gare station" },
      { e: "✈️", k: "avion airplane plane" },
      { e: "🛫", k: "decollage departure" },
      { e: "🛬", k: "atterrissage arrival" },
      { e: "🛩️", k: "petit avion" },
      { e: "💺", k: "siege seat" },
      { e: "🛰️", k: "satellite" },
      { e: "🚀", k: "fusee rocket launch" },
      { e: "🛸", k: "ovni ufo" },
      { e: "🚁", k: "helicoptere helicopter" },
      { e: "🛶", k: "canoe" },
      { e: "⛵", k: "voile sailboat" },
      { e: "🚤", k: "hors bord speedboat" },
      { e: "🛥️", k: "bateau moteur" },
      { e: "🛳️", k: "paquebot passenger" },
      { e: "⛴️", k: "ferry" },
      { e: "🚢", k: "navire ship" },
      { e: "⚓", k: "ancre anchor" },
      { e: "🪝", k: "crochet hook" },
      { e: "⛽", k: "essence fuel pump" },
      { e: "🚧", k: "travaux construction" },
      { e: "🚦", k: "feu tricolore traffic" },
      { e: "🚥", k: "feu horizontal" },
      { e: "🚏", k: "arret bus stop" },
      { e: "🗺️", k: "carte map" },
      { e: "🗿", k: "moai" },
      { e: "🗽", k: "statue liberte liberty" },
      { e: "🗼", k: "tour tokyo tower" },
      { e: "🏰", k: "chateau castle" },
      { e: "🏯", k: "chateau japonais" },
      { e: "🏟️", k: "stade stadium" },
      { e: "🎡", k: "grande roue ferris" },
      { e: "🎢", k: "montagnes russes roller" },
      { e: "🎠", k: "manège carousel" },
      { e: "⛲", k: "fontaine fountain" },
      { e: "⛱️", k: "parasol beach" },
      { e: "🏖️", k: "plage beach" },
      { e: "🏝️", k: "ile island" },
      { e: "🏜️", k: "desert" },
      { e: "🌋", k: "volcan volcano" },
      { e: "⛰️", k: "montagne mountain" },
      { e: "🏔️", k: "montagne neige" },
      { e: "🗻", k: "mont fuji" },
      { e: "🏕️", k: "camping" },
      { e: "⛺", k: "tente tent" },
      { e: "🏠", k: "maison house home" },
      { e: "🏡", k: "maison jardin" },
      { e: "🏢", k: "immeuble office" },
      { e: "🏣", k: "poste japonaise" },
      { e: "🏤", k: "poste europe" },
      { e: "🏥", k: "hopital hospital" },
      { e: "🏦", k: "banque bank" },
      { e: "🏨", k: "hotel" },
      { e: "🏩", k: "love hotel" },
      { e: "🏪", k: "supérette convenience" },
      { e: "🏫", k: "ecole school" },
      { e: "🏬", k: "grand magasin department" },
      { e: "🏭", k: "usine factory" },
      { e: "💒", k: "mariage wedding" },
      { e: "⛪", k: "eglise church" },
      { e: "🕌", k: "mosquee mosque" },
      { e: "🕍", k: "synagogue" },
      { e: "🛕", k: "temple hindou" },
      { e: "🕋", k: "kaaba" },
      { e: "⛩️", k: "torii shrine" },
      { e: "🛤️", k: "voie ferree railway" },
      { e: "🛣️", k: "autoroute motorway" },
      { e: "🗾", k: "japon map" },
      { e: "🎑", k: "moon viewing" },
      { e: "🏞️", k: "parc national park" },
      { e: "🌅", k: "lever soleil sunrise" },
      { e: "🌄", k: "aube montagnes" },
      { e: "🌠", k: "etoile filante shooting" },
      { e: "🎇", k: "feu artifice sparkler" },
      { e: "🎆", k: "feux artifice fireworks" },
      { e: "🌇", k: "coucher immeubles sunset" },
      { e: "🌆", k: "ville crepuscule dusk" },
      { e: "🏙️", k: "skyline ville city" },
      { e: "🌃", k: "nuit etoiles night" },
      { e: "🌌", k: "voie lactee milky way" },
      { e: "🌉", k: "pont night bridge" },
      { e: "🌁", k: "brouillard foggy" }
    ]
  },
  {
    id: "objects",
    icon: "mdi:lightbulb-outline",
    emojis: [
      { e: "⌚", k: "montre watch" },
      { e: "📱", k: "telephone mobile phone" },
      { e: "📲", k: "telephone fleche" },
      { e: "💻", k: "ordinateur laptop pc computer" },
      { e: "⌨️", k: "clavier keyboard" },
      { e: "🖥️", k: "ecran desktop" },
      { e: "🖨️", k: "imprimante printer" },
      { e: "🖱️", k: "souris mouse" },
      { e: "🖲️", k: "trackball" },
      { e: "🕹️", k: "joystick" },
      { e: "🗜️", k: "etau clamp" },
      { e: "💽", k: "minidisc" },
      { e: "💾", k: "disquette floppy save" },
      { e: "💿", k: "cd disc" },
      { e: "📀", k: "dvd" },
      { e: "📼", k: "vhs cassette" },
      { e: "📷", k: "appareil photo camera" },
      { e: "📸", k: "flash camera" },
      { e: "📹", k: "camera video" },
      { e: "🎥", k: "camera cinema" },
      { e: "📽️", k: "projecteur film" },
      { e: "🎞️", k: "pellicule frames" },
      { e: "📞", k: "telephone receiver" },
      { e: "☎️", k: "telephone fixe" },
      { e: "📟", k: "pager" },
      { e: "📠", k: "fax" },
      { e: "📺", k: "television tv" },
      { e: "📻", k: "radio" },
      { e: "🎙️", k: "micro studio" },
      { e: "🎚️", k: "niveau level" },
      { e: "🎛️", k: "boutons control" },
      { e: "🧭", k: "boussole compass" },
      { e: "⏱️", k: "chronometre stopwatch" },
      { e: "⏲️", k: "minuteur timer" },
      { e: "⏰", k: "reveil alarm clock" },
      { e: "🕰️", k: "horloge mantel" },
      { e: "⌛", k: "sablier hourglass done" },
      { e: "⏳", k: "sablier hourglass" },
      { e: "📡", k: "antenne satellite" },
      { e: "🔋", k: "batterie battery" },
      { e: "🔌", k: "prise plug" },
      { e: "💡", k: "ampoule idee idea light bulb" },
      { e: "🔦", k: "lampe torche flashlight" },
      { e: "🕯️", k: "bougie candle" },
      { e: "🪔", k: "diya lamp" },
      { e: "🧯", k: "extincteur extinguisher" },
      { e: "🛢️", k: "baril oil" },
      { e: "💸", k: "argent wings money" },
      { e: "💵", k: "dollar billet" },
      { e: "💴", k: "yen" },
      { e: "💶", k: "euro" },
      { e: "💷", k: "livre pound" },
      { e: "🪙", k: "piece coin" },
      { e: "💰", k: "sac argent money bag" },
      { e: "💳", k: "carte credit card" },
      { e: "💎", k: "diamant gem" },
      { e: "⚖️", k: "balance justice scale" },
      { e: "🪜", k: "echelle ladder" },
      { e: "🧰", k: "boite outils toolbox" },
      { e: "🪛", k: "tournevis screwdriver" },
      { e: "🔧", k: "cle plate wrench outil" },
      { e: "🔨", k: "marteau hammer" },
      { e: "⚒️", k: "marteau pioche" },
      { e: "🛠️", k: "marteau cle tools" },
      { e: "⛏️", k: "pioche pick" },
      { e: "🪚", k: "scie saw" },
      { e: "🔩", k: "boulon nut bolt" },
      { e: "⚙️", k: "engrenage gear" },
      { e: "🪤", k: "piege trap" },
      { e: "🧱", k: "brique brick" },
      { e: "⛓️", k: "chaine chains" },
      { e: "🧲", k: "aimant magnet" },
      { e: "🔫", k: "pistolet gun" },
      { e: "💣", k: "bombe bomb" },
      { e: "🧨", k: "petard firecracker" },
      { e: "🪓", k: "hache axe" },
      { e: "🔪", k: "couteau knife" },
      { e: "🗡️", k: "dague dagger" },
      { e: "⚔️", k: "epees crossed swords" },
      { e: "🛡️", k: "bouclier shield" },
      { e: "🚬", k: "cigarette" },
      { e: "⚰️", k: "cercueil coffin" },
      { e: "🪦", k: "pierre tombale headstone" },
      { e: "⚱️", k: "urne" },
      { e: "🏺", k: "amphore" },
      { e: "🔮", k: "boule cristal crystal" },
      { e: "📿", k: "chapelet beads" },
      { e: "🧿", k: "nazar oeil" },
      { e: "💈", k: "barber pole" },
      { e: "⚗️", k: "alambic alembic" },
      { e: "🔭", k: "telescope" },
      { e: "🔬", k: "microscope" },
      { e: "🕳️", k: "trou hole" },
      { e: "🩹", k: "pansement bandage" },
      { e: "🩺", k: "stethoscope" },
      { e: "💊", k: "pilule pill" },
      { e: "💉", k: "seringue syringe" },
      { e: "🩸", k: "sang blood" },
      { e: "🧬", k: "adn dna" },
      { e: "🦠", k: "microbe virus" },
      { e: "🧫", k: "petri" },
      { e: "🧪", k: "tube a essai test tube" },
      { e: "🌡️", k: "thermometre" },
      { e: "🧹", k: "balai broom" },
      { e: "🪠", k: "ventouse plunger" },
      { e: "🧺", k: "panier basket" },
      { e: "🧻", k: "papier toilette roll" },
      { e: "🚽", k: "toilettes toilet" },
      { e: "🚰", k: "eau potable potable" },
      { e: "🚿", k: "douche shower" },
      { e: "🛁", k: "baignoire bathtub" },
      { e: "🛀", k: "bain bath" },
      { e: "🧼", k: "savon soap" },
      { e: "🪥", k: "brosse dents toothbrush" },
      { e: "🪒", k: "rasoir razor" },
      { e: "🧴", k: "lotion bouteille" },
      { e: "🧽", k: "eponge sponge" },
      { e: "🛒", k: "caddie cart" },
      { e: "🚪", k: "porte door" },
      { e: "🪞", k: "miroir mirror" },
      { e: "🪟", k: "fenetre window" },
      { e: "🛏️", k: "lit bed" },
      { e: "🛋️", k: "canape couch" },
      { e: "🪑", k: "chaise chair" },
      { e: "🧸", k: "ours en peluche teddy" },
      { e: "🪆", k: "poupées russes nesting" },
      { e: "🖼️", k: "cadre framed picture" },
      { e: "🛍️", k: "sacs shopping" },
      { e: "🎈", k: "ballon balloon" },
      { e: "🎏", k: "koinobori" },
      { e: "🎀", k: "ruban ribbon" },
      { e: "🎁", k: "cadeau gift present" },
      { e: "🎊", k: "confettis" },
      { e: "🎉", k: "fete party popper celebrate" },
      { e: "🎎", k: "poupées" },
      { e: "🏮", k: "lanterne" },
      { e: "🎐", k: "carillon wind" },
      { e: "🧧", k: "enveloppe rouge" },
      { e: "✉️", k: "enveloppe email letter mail" },
      { e: "📩", k: "enveloppe fleche" },
      { e: "📨", k: "enveloppe incoming" },
      { e: "📧", k: "email e-mail" },
      { e: "💌", k: "lettre amour love letter" },
      { e: "📥", k: "boite reception inbox" },
      { e: "📤", k: "boite envoi outbox" },
      { e: "📦", k: "colis package box" },
      { e: "🏷️", k: "etiquette label tag" },
      { e: "🪧", k: "pancarte placard" },
      { e: "📪", k: "boite lettres fermee" },
      { e: "📫", k: "boite lettres ouverte" },
      { e: "📬", k: "boite avec courrier" },
      { e: "📭", k: "boite sans courrier" },
      { e: "📮", k: "boite postale postbox" },
      { e: "📯", k: "cor postal" },
      { e: "📜", k: "parchemin scroll" },
      { e: "📃", k: "page curl" },
      { e: "📄", k: "page document" },
      { e: "📑", k: "marque pages bookmark tabs" },
      { e: "🧾", k: "recu receipt" },
      { e: "📊", k: "graphique bar chart stats" },
      { e: "📈", k: "graphique hausse chart up" },
      { e: "📉", k: "graphique baisse chart down" },
      { e: "🗒️", k: "bloc notes notepad" },
      { e: "🗓️", k: "calendrier spiral" },
      { e: "📆", k: "calendrier tear off" },
      { e: "📅", k: "calendrier calendar date" },
      { e: "🗑️", k: "poubelle trash" },
      { e: "📇", k: "fichier card index" },
      { e: "🗃️", k: "boite fichiers" },
      { e: "🗳️", k: "urne vote ballot" },
      { e: "🗄️", k: "classeurs file cabinet" },
      { e: "📋", k: "presse papiers clipboard" },
      { e: "📁", k: "dossier folder" },
      { e: "📂", k: "dossier ouvert" },
      { e: "🗂️", k: "separateurs dividers" },
      { e: "🗞️", k: "journal rolled" },
      { e: "📰", k: "journal newspaper" },
      { e: "📓", k: "carnet notebook" },
      { e: "📔", k: "carnet deco" },
      { e: "📒", k: "registre ledger" },
      { e: "📕", k: "livre ferme book" },
      { e: "📗", k: "livre vert" },
      { e: "📘", k: "livre bleu" },
      { e: "📙", k: "livre orange" },
      { e: "📚", k: "livres books" },
      { e: "📖", k: "livre ouvert open book" },
      { e: "🔖", k: "marque page bookmark" },
      { e: "🧷", k: "epingle safety pin" },
      { e: "🔗", k: "lien link chaine" },
      { e: "📎", k: "trombone paperclip" },
      { e: "🖇️", k: "trombones linked" },
      { e: "📐", k: "equerre triangle" },
      { e: "📏", k: "regle ruler" },
      { e: "🧮", k: "abaque abacus" },
      { e: "📌", k: "epingle pin pushpin" },
      { e: "📍", k: "epingle ronde round pin location" },
      { e: "✂️", k: "ciseaux scissors" },
      { e: "🖊️", k: "stylo pen" },
      { e: "🖋️", k: "stylo plume fountain" },
      { e: "✒️", k: "plume nib" },
      { e: "🖌️", k: "pinceau paintbrush" },
      { e: "🖍️", k: "crayon cire crayon" },
      { e: "📝", k: "memo note ecrire write" },
      { e: "✏️", k: "crayon pencil" },
      { e: "🔍", k: "loupe gauche search" },
      { e: "🔎", k: "loupe droite search" },
      { e: "🔏", k: "cadenas encre lock" },
      { e: "🔐", k: "cadenas cle locked key" },
      { e: "🔒", k: "cadenas lock locked" },
      { e: "🔓", k: "cadenas ouvert unlock" }
    ]
  },
  {
    id: "symbols",
    icon: "mdi:heart-outline",
    emojis: [
      { e: "❤️", k: "coeur rouge heart love" },
      { e: "🧡", k: "coeur orange" },
      { e: "💛", k: "coeur jaune" },
      { e: "💚", k: "coeur vert" },
      { e: "💙", k: "coeur bleu" },
      { e: "💜", k: "coeur violet" },
      { e: "🖤", k: "coeur noir" },
      { e: "🤍", k: "coeur blanc" },
      { e: "🤎", k: "coeur marron" },
      { e: "💔", k: "coeur brise broken" },
      { e: "❣️", k: "exclamation coeur" },
      { e: "💕", k: "deux coeurs" },
      { e: "💞", k: "coeurs tournants" },
      { e: "💓", k: "coeur battant beating" },
      { e: "💗", k: "coeur grandissant growing" },
      { e: "💖", k: "coeur etincelant sparkling" },
      { e: "💘", k: "coeur fleche cupidon" },
      { e: "💝", k: "coeur ruban" },
      { e: "💟", k: "decoration coeur" },
      { e: "☮️", k: "paix peace" },
      { e: "✝️", k: "croix latine" },
      { e: "☪️", k: "etoile croissant islam" },
      { e: "🕉️", k: "om" },
      { e: "☸️", k: "roue dharma" },
      { e: "✡️", k: "etoile david" },
      { e: "🔯", k: "etoile six" },
      { e: "🕎", k: "menorah" },
      { e: "☯️", k: "yin yang" },
      { e: "☦️", k: "croix orthodoxe" },
      { e: "🛐", k: "lieu culte worship" },
      { e: "⛎", k: "ophiuchus" },
      { e: "♈", k: "belier aries" },
      { e: "♉", k: "taureau taurus" },
      { e: "♊", k: "gemeaux gemini" },
      { e: "♋", k: "cancer" },
      { e: "♌", k: "lion leo" },
      { e: "♍", k: "vierge virgo" },
      { e: "♎", k: "balance libra" },
      { e: "♏", k: "scorpion scorpio" },
      { e: "♐", k: "sagittaire sagittarius" },
      { e: "♑", k: "capricorne capricorn" },
      { e: "♒", k: "verseau aquarius" },
      { e: "♓", k: "poissons pisces" },
      { e: "🆔", k: "id" },
      { e: "⚛️", k: "atome atom" },
      { e: "🉑", k: "accept" },
      { e: "☢️", k: "radioactif radioactive" },
      { e: "☣️", k: "biohazard" },
      { e: "📴", k: "telephone off" },
      { e: "📳", k: "vibreur vibration" },
      { e: "🈶", k: "not free" },
      { e: "🈚", k: "free of charge" },
      { e: "🈸", k: "application" },
      { e: "🈺", k: "open for business" },
      { e: "🈷️", k: "monthly" },
      { e: "✴️", k: "etoile huit" },
      { e: "🆚", k: "vs versus" },
      { e: "💮", k: "fleur blanche" },
      { e: "🉐", k: "avantage bargain" },
      { e: "㊙️", k: "secret" },
      { e: "㊗️", k: "felicitations congratulations" },
      { e: "🈴", k: "passing grade" },
      { e: "🈵", k: "complet full" },
      { e: "🈹", k: "reduction discount" },
      { e: "🈲", k: "interdit prohibited" },
      { e: "🅰️", k: "a blood" },
      { e: "🅱️", k: "b blood" },
      { e: "🆎", k: "ab blood" },
      { e: "🆑", k: "cl" },
      { e: "🅾️", k: "o blood" },
      { e: "🆘", k: "sos aide help urgence" },
      { e: "❌", k: "croix x no error" },
      { e: "⭕", k: "cercle o" },
      { e: "🛑", k: "stop" },
      { e: "⛔", k: "sens interdit no entry" },
      { e: "📛", k: "badge nom" },
      { e: "🚫", k: "interdit prohibited" },
      { e: "💯", k: "100 cent parfait score" },
      { e: "💢", k: "colere anger" },
      { e: "♨️", k: "sources chaudes hotsprings" },
      { e: "🚷", k: "pietons interdits" },
      { e: "🚯", k: "ne pas jeter" },
      { e: "🚳", k: "velos interdits" },
      { e: "🚱", k: "eau non potable" },
      { e: "🔞", k: "18 plus mineur" },
      { e: "📵", k: "telephone interdit" },
      { e: "🚭", k: "interdiction fumer" },
      { e: "❗", k: "exclamation important" },
      { e: "❕", k: "exclamation blanche" },
      { e: "❓", k: "question" },
      { e: "❔", k: "question blanche" },
      { e: "‼️", k: "double exclamation" },
      { e: "⁉️", k: "exclamation question" },
      { e: "🔅", k: "luminosite basse" },
      { e: "🔆", k: "luminosite haute" },
      { e: "〽️", k: "part alternation" },
      { e: "⚠️", k: "attention warning danger" },
      { e: "🚸", k: "enfants children crossing" },
      { e: "🔱", k: "trident" },
      { e: "⚜️", k: "fleur de lys" },
      { e: "🔰", k: "debutant japanese" },
      { e: "♻️", k: "recyclage recycle" },
      { e: "✅", k: "check vert ok valide done" },
      { e: "🈯", k: "reserved" },
      { e: "💹", k: "marche yen chart" },
      { e: "❇️", k: "sparkle" },
      { e: "✳️", k: "eight spoked" },
      { e: "❎", k: "croix bouton" },
      { e: "🌐", k: "globe meridiens www internet" },
      { e: "💠", k: "diamant a pois" },
      { e: "Ⓜ️", k: "m cercle metro" },
      { e: "🌀", k: "cyclone spiral" },
      { e: "💤", k: "zzz dodo sleep" },
      { e: "🏧", k: "atm" },
      { e: "🚾", k: "wc toilettes" },
      { e: "♿", k: "accessibilite wheelchair" },
      { e: "🅿️", k: "parking" },
      { e: "🛗", k: "ascenseur elevator" },
      { e: "🈳", k: "vacancy" },
      { e: "🈂️", k: "service charge" },
      { e: "🛂", k: "passeport control" },
      { e: "🛃", k: "douane customs" },
      { e: "🛄", k: "bagages baggage" },
      { e: "🛅", k: "consigne locker" },
      { e: "🚹", k: "hommes mens" },
      { e: "🚺", k: "femmes womens" },
      { e: "🚼", k: "bebe baby" },
      { e: "🚻", k: "toilettes restroom" },
      { e: "🚮", k: "poubelle litter" },
      { e: "🎦", k: "cinema" },
      { e: "📶", k: "signal antenna bars reseau" },
      { e: "🈁", k: "ici here" },
      { e: "🔣", k: "symboles" },
      { e: "ℹ️", k: "info information" },
      { e: "🔤", k: "abc latin" },
      { e: "🔡", k: "abcd minuscules" },
      { e: "🔠", k: "abcd majuscules" },
      { e: "🔢", k: "1234 chiffres numbers" },
      { e: "🔟", k: "10 keycap" },
      { e: "#️⃣", k: "hash diese" },
      { e: "*️⃣", k: "asterisque" },
      { e: "⏏️", k: "eject" },
      { e: "▶️", k: "play lecture" },
      { e: "⏸️", k: "pause" },
      { e: "⏯️", k: "play pause" },
      { e: "⏹️", k: "stop" },
      { e: "⏺️", k: "record" },
      { e: "⏭️", k: "next track" },
      { e: "⏮️", k: "previous track" },
      { e: "⏩", k: "avance fast" },
      { e: "⏪", k: "retour rewind" },
      { e: "⏫", k: "fast up" },
      { e: "⏬", k: "fast down" },
      { e: "◀️", k: "reverse" },
      { e: "🔼", k: "up button" },
      { e: "🔽", k: "down button" },
      { e: "➡️", k: "fleche droite right" },
      { e: "⬅️", k: "fleche gauche left" },
      { e: "⬆️", k: "fleche haut up" },
      { e: "⬇️", k: "fleche bas down" },
      { e: "↗️", k: "fleche nord est" },
      { e: "↘️", k: "fleche sud est" },
      { e: "↙️", k: "fleche sud ouest" },
      { e: "↖️", k: "fleche nord ouest" },
      { e: "↕️", k: "fleche haut bas" },
      { e: "↔️", k: "fleche gauche droite" },
      { e: "↪️", k: "fleche courbe droite" },
      { e: "↩️", k: "fleche courbe gauche" },
      { e: "⤴️", k: "fleche courbe haut" },
      { e: "⤵️", k: "fleche courbe bas" },
      { e: "🔀", k: "aleatoire shuffle" },
      { e: "🔁", k: "repetition repeat" },
      { e: "🔂", k: "repetition un" },
      { e: "🔄", k: "refresh actualiser" },
      { e: "🔃", k: "horloge vertical" },
      { e: "🎵", k: "note musique music" },
      { e: "🎶", k: "notes musique music" },
      { e: "➕", k: "plus add" },
      { e: "➖", k: "moins minus" },
      { e: "➗", k: "diviser divide" },
      { e: "✖️", k: "multiplier multiply" },
      { e: "♾️", k: "infini infinity" },
      { e: "💲", k: "dollar heavy" },
      { e: "💱", k: "change currency" },
      { e: "™️", k: "tm trademark" },
      { e: "©️", k: "copyright" },
      { e: "®️", k: "registered" },
      { e: "👁️‍🗨️", k: "oeil bulle witness" },
      { e: "🔚", k: "end" },
      { e: "🔙", k: "back" },
      { e: "🔛", k: "on" },
      { e: "🔝", k: "top" },
      { e: "🔜", k: "soon" },
      { e: "〰️", k: "vague dash" },
      { e: "➰", k: "boucle curly" },
      { e: "➿", k: "double boucle" },
      { e: "✔️", k: "check mark" },
      { e: "☑️", k: "case cochee ballot" },
      { e: "🔘", k: "bouton radio" },
      { e: "🔴", k: "rond rouge red" },
      { e: "🟠", k: "rond orange" },
      { e: "🟡", k: "rond jaune" },
      { e: "🟢", k: "rond vert green" },
      { e: "🔵", k: "rond bleu blue" },
      { e: "🟣", k: "rond violet" },
      { e: "⚫", k: "rond noir" },
      { e: "⚪", k: "rond blanc" },
      { e: "🟤", k: "rond marron" },
      { e: "🔺", k: "triangle rouge haut" },
      { e: "🔻", k: "triangle rouge bas" },
      { e: "🔸", k: "petit losange orange" },
      { e: "🔹", k: "petit losange bleu" },
      { e: "🔶", k: "grand losange orange" },
      { e: "🔷", k: "grand losange bleu" },
      { e: "🔳", k: "bouton blanc carre" },
      { e: "🔲", k: "bouton noir carre" },
      { e: "▪️", k: "petit carre noir" },
      { e: "▫️", k: "petit carre blanc" },
      { e: "◾", k: "carre moyen noir" },
      { e: "◽", k: "carre moyen blanc" },
      { e: "◼️", k: "carre noir" },
      { e: "◻️", k: "carre blanc" },
      { e: "🟥", k: "carre rouge" },
      { e: "🟧", k: "carre orange" },
      { e: "🟨", k: "carre jaune" },
      { e: "🟩", k: "carre vert" },
      { e: "🟦", k: "carre bleu" },
      { e: "🟪", k: "carre violet" },
      { e: "⬛", k: "grand carre noir" },
      { e: "⬜", k: "grand carre blanc" },
      { e: "🟫", k: "carre marron" },
      { e: "🔈", k: "volume bas speaker" },
      { e: "🔇", k: "muet mute" },
      { e: "🔉", k: "volume moyen" },
      { e: "🔊", k: "volume haut loud" },
      { e: "🔔", k: "cloche bell notif" },
      { e: "🔕", k: "cloche barree mute" },
      { e: "📣", k: "megaphone" },
      { e: "📢", k: "haut parleur loudspeaker" },
      { e: "💬", k: "bulle speech comment" },
      { e: "💭", k: "bulle pensee thought" },
      { e: "🗯️", k: "bulle colere anger" },
      { e: "♠️", k: "pique spade" },
      { e: "♣️", k: "trefle club" },
      { e: "♥️", k: "coeur carte heart" },
      { e: "♦️", k: "carreau diamond" },
      { e: "🃏", k: "joker" },
      { e: "🎴", k: "cartes fleur" },
      { e: "🀄", k: "mahjong" },
      { e: "🕐", k: "1h clock" },
      { e: "🕑", k: "2h clock" },
      { e: "🕒", k: "3h clock" },
      { e: "🕓", k: "4h clock" },
      { e: "🕔", k: "5h clock" },
      { e: "🕕", k: "6h clock" },
      { e: "🕖", k: "7h clock" },
      { e: "🕗", k: "8h clock" },
      { e: "🕘", k: "9h clock" },
      { e: "🕙", k: "10h clock" },
      { e: "🕚", k: "11h clock" },
      { e: "🕛", k: "12h midi minuit clock" },
      { e: "🏳️", k: "drapeau blanc white flag" },
      { e: "🏴", k: "drapeau noir black flag" },
      { e: "🏁", k: "drapeau damier checkered" },
      { e: "🚩", k: "drapeau triangulaire" },
      { e: "🏳️‍🌈", k: "rainbow pride lgbt" },
      { e: "🏳️‍⚧️", k: "transgenre transgender" },
      { e: "🏴‍☠️", k: "pirate" },
      { e: "🇫🇷", k: "france french fr" },
      { e: "🇧🇪", k: "belgique belgium be" },
      { e: "🇨🇭", k: "suisse switzerland ch" },
      { e: "🇨🇦", k: "canada ca" },
      { e: "🇬🇧", k: "royaume uni uk gb britain" },
      { e: "🇺🇸", k: "etats unis usa us america" },
      { e: "🇩🇪", k: "allemagne germany de" },
      { e: "🇮🇹", k: "italie italy it" },
      { e: "🇪🇸", k: "espagne spain es" },
      { e: "🇵🇹", k: "portugal pt" },
      { e: "🇳🇱", k: "pays bas netherlands nl" },
      { e: "🇱🇺", k: "luxembourg lu" },
      { e: "🇪🇺", k: "europe union eu" },
      { e: "🇯🇵", k: "japon japan jp" },
      { e: "🇨🇳", k: "chine china cn" },
      { e: "🇲🇦", k: "maroc morocco ma" },
      { e: "🇹🇳", k: "tunisie tunisia tn" },
      { e: "🇩🇿", k: "algerie algeria dz" },
      { e: "🇸🇳", k: "senegal sn" },
      { e: "🇨🇮", k: "cote ivoire ci" },
      { e: "🇧🇷", k: "bresil brazil br" },
      { e: "🇦🇺", k: "australie australia au" }
    ]
  }
];

export const ALL_EMOJIS = (() => {
  const seen = new Set();
  const list = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const item of category.emojis) {
      if (seen.has(item.e)) continue;
      seen.add(item.e);
      list.push(item);
    }
  }
  return list;
})();

export function normalizeEmojiQuery(value) {
  return String(value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

export function searchEmojis(query, limit = 180) {
  const needle = normalizeEmojiQuery(query);
  if (!needle) return ALL_EMOJIS;
  const starts = [];
  const contains = [];
  for (const item of ALL_EMOJIS) {
    const normalized = normalizeEmojiQuery(`${item.e} ${item.k}`);
    if (normalized.split(/[\s,]+/).some(token => token.startsWith(needle))) {
      starts.push(item);
    } else if (normalized.includes(needle)) {
      contains.push(item);
    }
  }
  return [...starts, ...contains].slice(0, limit);
}

export function loadRecentEmojis() {
  try {
    const raw = localStorage.getItem(EMOJI_RECENT_STORAGE_KEY);
    const parsed = JSON.parse(raw || "[]");
    if (!Array.isArray(parsed)) return [];
    return parsed.map(item => String(item || "")).filter(Boolean).slice(0, EMOJI_RECENT_LIMIT);
  } catch {
    return [];
  }
}

export function rememberRecentEmoji(emoji) {
  const next = [emoji, ...loadRecentEmojis().filter(item => item !== emoji)].slice(0, EMOJI_RECENT_LIMIT);
  try {
    localStorage.setItem(EMOJI_RECENT_STORAGE_KEY, JSON.stringify(next));
  } catch {
    /* ignore quota */
  }
  return next;
}
